on:
  push:
    branches:
      - dev
      - qa
      - main

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        type: choice
        options:
          - dev
          - qa
          - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout the appropriate branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref_name }}
          fetch-depth: 0

      - name: Fetch additional branches
        run: |
          git fetch origin dev:refs/remotes/origin/dev
          git fetch origin qa:refs/remotes/origin/qa
          git fetch origin main:refs/remotes/origin/main

      - name: List branches
        run: git branch -a
