name: Central Branch Build Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        type: choice
        options:
          - dev
          - qa
          - main

  repository_dispatch:
    types: [trigger-central-workflow]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.event.client_payload.branch }}
          fetch-depth: 0

      - name: Fetch all branches
        run: |
          git fetch origin dev:refs/remotes/origin/dev
          git fetch origin qa:refs/remotes/origin/qa
          git fetch origin main:refs/remotes/origin/main

      - name: List branches (debug)
        run: git branch -a

      - name: Run branch-specific logic
        run: |
          BRANCH="${{ github.event.inputs.branch || github.event.client_payload.branch }}"
          echo "Triggered for branch: $BRANCH"
